### ISSUE TITLE
jeetsi-meet with the adapter installed looses the ability to redirect login to oidc IDP after each jitsi-meet apt update

### ISSUE THREAD

**Issue by dutty5** [nordeck/jitsi-keycloak-adapter#28]
I use this adapter successfully for about a year. I have the standalone installation described here: https://github.com/nordeck/jitsi-keycloak-adapter/blob/main/docs/setup-standalone.md

This setup basically works fine. However, after each jitsi-meet update with the apt it looses its ability to redirect unauthenticated users to the oidc IDP. I need to go all over the standalone setup procedure from the beginning to make it work again.

I mentioned this problem here: https://github.com/nordeck/jitsi-keycloak-adapter/issues/22#issuecomment-2407670540

In other words, if a user is not authorized the login redirection stops working (after the apt update), however if a user already has an active authorized session with his IDP prior to visiting Jitsi meet, then that authorization also continues to work for Jitsi. If I repeat the standalone configuration from the beginning, everything starts working again as it did before the update.

So I believe Jitsi meet updates overwrite some configuration changes (or files) that we make with the standalone setup. Is there a way to make the configuration persistent?

**Comment by emrahcom** [comment]
Hi @dutty5,

There are [some files](https://github.com/nordeck/jitsi-keycloak-adapter/blob/main/docs/setup-standalone.md#32-static-files) in `/usr/share/jitsi-meet` folder which are added or customized for the adapter. These files should be updated again after each upgrade since the upgrade process recreates this folder.

As an alternative you may try the second generation of [jitsi-keycloak-adapter](https://github.com/nordeck/jitsi-keycloak-adapter-v2) which doesn't use these static files.

**Comment by dutty5** [comment]
I see. Thank you for pointing me to the relevant section in the readme. It will save my time the next time after the update.
